version: '3.9'
services:
  redis:
    image: 'redis/redis-stack'
    ports:
      - '6379:6379'
      - '8001:8001'
  web1:
    restart: on-failure
    build: ./
    ports:
      - '3001:3001'
  nginx:
    build: ./nginx
    ports:
    - '2022:80'
    depends_on:
    - web1
