version: '3.9'
services:
# redis GUI tool
  insight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    volumes: []
    restart: on-failure
    depends_on:
      - redis_words
      - redis_auth
# redis db
  redis_words:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  
  redis_auth:
      image: redislabs/redismod
      ports:
        - "6380:6379"
      restart: on-failure
# node service/app
  web1:
    restart: on-failure
    build: ./
    ports:
      - '3001:3001'
# reverse proxy as a loadbalancer
  nginx:
    build: ./nginx
    ports:
      - '2022:80'
    depends_on:
      - web1
