version: '3.9'
services:


  # redis GUI tool
  insight:
    image: redislabs/redisinsight
    ports:
      - '8001:8001'
    volumes:
      - /var/lib/docker/volumes/redisinsight/_data:/data
    restart: unless-stopped
    depends_on:
      - redis_words
      - redis_auth



  # redis db
  redis_words:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    volumes:
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /var/lib/docker/volumes/redis_words/_data:/data
    entrypoint: >
        redis-server
        --appendonly yes
        --maxmemory 1073741824
    restart: unless-stopped

    # command: "redis-server --bind web1 insight"



  redis_auth:
    image: redislabs/redismod
    ports:
      - '6380:6379'
    volumes:
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /var/lib/docker/volumes/redis_auth/_data:/data
    # command: "redis-server --bind web1 insight"



    # node service/app
  web1:
    build: ./
    ports:
      - '3001:3001'
    volumes:
      - /var/lib/docker/volumes/node_server/_data:/data
    restart: unless-stopped



  # reverse proxy as a loadbalancer
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web1
    volumes:
      - /var/lib/docker/volumes/nginx/_data:/data
    restart: unless-stopped
